### ISSUE TITLE
How to set threshold for TP Calculation?

### ISSUE THREAD

**Issue by aymuos15** [BrainLesion/panoptica#103]
_**Apologies if mentioned already somewhere**_, but currently the IoU Threshold for TP is set to 0.5 (I think?). How do I change that?

**Comment by Hendrik-code** [comment]
If you use a matcher, you need to specify the threshold there:
For the "NaiveThresholdMatching" algorithm, you can find this in panoptica/instance_matcher.py
![image](https://github.com/BrainLesion/panoptica/assets/19862882/4a1b73ff-ba43-4c28-89eb-9ef50702e8b3)

If you start with MatchedInstancePairs and you don't need matching anymore, you can control this variable with the "decision_threshold" and corresponding "decision_metric"
