### ISSUE TITLE
cannot import name 'Panoptic_Evaluator' from 'panoptica' 

### ISSUE THREAD

**Issue by aymuos15** [BrainLesion/panoptica#112]
**Describe the bug**
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-10-c979ef33b3fb>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from panoptica import (
      2     ConnectedComponentsInstanceApproximator,
      3     NaiveThresholdMatching,
      4     Panoptic_Evaluator,
      5     SemanticPair,

ImportError: cannot import name 'Panoptic_Evaluator' from 'panoptica' (/usr/local/lib/python3.10/dist-packages/panoptica/__init__.py)
```

**To Reproduce**
https://colab.research.google.com/drive/1eSC0GHUS6ykhwhFwWGWehUIFY-zfgGRw?usp=sharing
(Just run all)

**Expected behavior**
Should work normally as per the tutorials? Alos, Where is `Panoptic_Evaluator` coming from exactly?

**Environment**
Colab

### version of panoptica ?
Latest

**Comment by Hendrik-code** [comment]
It is named Panoptica_Evaluator now.
Hope this helps =)

**Comment by aymuos15** [comment]
Right, that's what was in the init as well. Thanks a lot for the quick responses always!
