### ISSUE TITLE
RuntimeWarning: Degrees of freedom <= 0 for slice

### ISSUE THREAD

**Issue by JosefBuchner** [BrainLesion/panoptica#31]
I am encountering the following warning when using the Panoptic_Evaluator on a SemanticPair: 

`/home/josef/miniconda3/envs/panoptica/lib/python3.12/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/josef/miniconda3/envs/panoptica/lib/python3.12/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/josef/miniconda3/envs/panoptica/lib/python3.12/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)`

I am running panoptica 0.53 and Python 3.12.

**Comment by neuronflow** [comment]
fixed with https://github.com/BrainLesion/panoptica/releases/tag/v0.5.6
