### ISSUE TITLE
Semantic Segmentation: different MRI slice in the reference and predicition picture

### ISSUE THREAD

**Issue by evamariie** [BrainLesion/panoptica#93]
The sMRI slices in reference and prediction of the semantic segmentation spinal MRI "picture" seems not to be the exact same slice. 
![semantic_segementation_pic](https://github.com/BrainLesion/panoptica/assets/106267274/c9bc73df-5f23-41a1-bc8f-a05c39a07233)

**Comment by neuronflow** [comment]
@MarcelRosier this also affects the tutorials :)
